### PR TITLE
Implement Status interface

### PR DESCRIPTION
**Pull request by syuilo**

### CODE REVIEW

**Comment by AyaMorisawa** [comment]
tsconfig.jsonにstatus.tsを含めるようにしてください

**Comment by syuilo** [comment]
Added

**Comment by AyaMorisawa** [comment]
merged in 3053d9f9ae4d8397bf3e34f9cf5b47363f8294f3

**Comment by AyaMorisawa** [comment]
merged in 11d19fe097725d63264a2af8a661f8a0e5be6f24

**Pull request closed without merging**
